In [3]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\user\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\user\anaconda3\lib\site-packages (from selenium) (1.25.11)

In [5]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

In [6]:
driver = webdriver.Chrome("chromedriver.exe")

.Question 1-write a python program to scrape data for "Data Analyst" job position in "Bangalore" location.You have to scrape the job-title,job-location,company_name,experiance_required.you have to scrape first 10 job data.

In [ ]:
#Q1.webpage
url = 'https://www.naukri.com/'  
driver.get(url)

#Enter "Data Analyst" in "Skill,Designations,Comapnies" field
search_job = driver.find_element_by_id('qsb-keyword-sugg')
search_job.send_keys("Data Analyst")


#enter"Bangalore"in "enter the location"field
search_loc = driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys("Bangalore")

#Click the search button
search_btn = driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

#scrape the job-title,job_location,campany_name,experiance_requried empty list.
job_titles=[]
campany_name=[]
experiance_list=[]
location_list=[]

#scrape the job-title
titles_tags= driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags
job_titles=[]
for i in titles_tags:
    job_titles.append(i.text)
job_titles

#top 10 job list
titles_tags[:10]


#scrape the campany_name.
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags
company_names=[]

for i in companies_tags:
    company_names.append(i.text)
company_names


#scrape the experiance_requried.
experiance_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")
experiance_tags
experiance_list=[]
for i in experiance_tags:
    experiance_list.append(i.text)
experiance_list

#scrape the job_location.
locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
locations_tags
locations_list=[]
for i in locations_tags:
    locations_list.append(i.text)
locations_list

print(len(job_titles),len(company_names),len(experiance_list),len(locations_list))

#DataFrame
jobs=pd.DataFrame({})
jobs['title']=job_titles
jobs['campany']=company_names
jobs['experiance_requried']=experiance_list
jobs['location']=locations_list

In [75]:
jobs

,title,campany,experiance_requried,location
0,Senior Data Analyst,Flipkart Internet Private Limited,4-5 Yrs,Bangalore/Bengaluru
1,Data Analyst (Data Stewards)//Immediate Joiner...,Tech Mahindra Ltd.,5-10 Yrs,Bangalore/Bengaluru
2,Senior Data Analyst,Publicis Groupe,5-9 Yrs,Bangalore/Bengaluru
3,Senior Data Analyst,Publicis Groupe,6-8 Yrs,Bangalore/Bengaluru
4,Senior Data Analyst,Publicis Groupe,1-7 Yrs,Bangalore/Bengaluru
5,Senior Associate - Data Analyst,Publicis Groupe,1-3 Yrs,Bangalore/Bengaluru
6,Data Analyst-Immediate Joiners,Brillio,4-6 Yrs,Bangalore/Bengaluru
7,Data Analyst,COLLABERA,2-4 Yrs,Bangalore/Bengaluru
8,Data Analyst,Allegis Services India Pvt. Ltd.,5-8 Yrs,Bangalore/Bengaluru
9,Data Analyst,Allegis Services India Pvt. Ltd.,8-12 Yrs,Bangalore/Bengaluru
10,Senior Data Analyst,Flipkart Internet Private Limited,2-5 Yrs,Bangalore/Bengaluru
11,Data Analyst,ANZ Banking Group,3-8 Yrs,Bangalore/Bengaluru
12,Sr Data Analyst with Hadoop and Alteryx both a...,Inspiration Manpower Consultancy Pvt. Ltd.,7-12 Yrs,Bangalore/Bengaluru
13,Senior Data Analyst,"Liventus, Inc.",5-8 Yrs,Bangalore/Bengaluru(2nd Phase JP Nagar)
14,Immediate job openings For Partner Consultant ...,RANDSTAD INDIA PVT LTD,1-5 Yrs,Bangalore/Bengaluru(Marathahalli)
15,"Data Analyst, Component Engineering",Rockwell Automation,2-3 Yrs,Bangalore/Bengaluru
16,Marketing Data analyst,Trifacta,2-5 Yrs,Bangalore/Bengaluru
17,Data Analyst,Colliers International India Property Service ...,2-6 Yrs,Bangalore/Bengaluru
18,Data Analyst,WEIWO Communication Pvt. Ltd.,5-8 Yrs,Bangalore/Bengaluru(Ulsoor)
19,"Business Analyst / Data Analyst - SQL Queries,...",Rivera Manpower Services,1-5 Yrs,Bangalore/Bengaluru

   Q2.write a python program to scrape data for "Data Scientist"

In [5]:
#1webpage
url = 'https://www.naukri.com/'  
driver.get(url)

#Enter "Data scientist" in "Skill,Designations,Comapnies" field
search_job = driver.find_element_by_id('qsb-keyword-sugg')
search_job
search_job.send_keys("Data Scientist")

#click search button
search_btn = driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [6]:
#fetching urls
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"):
    urls.append(i.get_attribute("href"))
    
len(urls)
urls

job_title=[]
job_description=[]

for i in urls[:10]:
    driver.get(i)
    time.sleep(3)
    #fetching job title
    try:
        job=driver.find_element_by_xpath("//h1[@class='jd-header-title']")
        job_title.append(job.text)
    except NoSuchElementException:
        job_title.append('-')
        
        #fetching job description
    try:
        job_desc= driver.find_element_by_xpath("//section[@class='job-desc']")
        job_descripton.append(job_desc.text)
    except:
        job_description.append('-')
        
print(len(job_title))
print(len(job_description))  

job_title
job_description

#DataFrame
jobs=pd.DataFrame({})
jobs['title']=job_titles
jobs['location']=locations_list
jobs['campany']=company_names
jobs['description']=job_description

10
10

NameError: name 'job_titles' is not defined

In [122]:
jobs

,title,campany,location
0,NaN,Flipkart Internet Private Limited,Bangalore/Bengaluru(Bellandur)
1,NaN,Flipkart Internet Private Limited,Bangalore/Bengaluru(Bellandur)
2,NaN,Myntra Designs Pvt. Ltd.,Bangalore/Bengaluru
3,NaN,Talent Corner HR Services Pvt Ltd,Bangalore/Bengaluru
4,NaN,HyrEzy Talent Solutions,Delhi / NCR
5,NaN,Devoted Health,Remote
6,NaN,Flipkart Internet Private Limited,Bangalore/Bengaluru
7,NaN,Mind Circus Innovation,"Mysore/Mysuru, Coimbatore, Bangalore/Bengaluru"
8,NaN,Mind Circus Innovation,"Madurai, Warangal, Hyderabad/Secunderabad"
9,NaN,Mind Circus Innovation,"Kochi/Cochin, Ernakulam, Trivandrum/Thiruvanan..."
10,NaN,Mind Circus Innovation,"Nagpur, Pune, Mumbai (All Areas)"
11,NaN,Mind Circus Innovation,"Pondicherry/Puducherry, Chennai, Tiruchirapall..."
12,NaN,GENPACT India Private Limited,Noida
13,NaN,PharmEasy,Bangalore/Bengaluru
14,NaN,Novel Office,Bangalore/Bengaluru
15,NaN,Schneider Electric,Bangalore/Bengaluru
16,NaN,Finxera,Chandigarh
17,NaN,Finxera,Chandigarh
18,NaN,IQVIA RDS India Pvt Ltd,"Bangalore/Bengaluru, Mumbai (All Areas)"
19,NaN,Flipkart Internet Private Limited,Bangalore/Bengaluru

Question 3-Data using the filters

In [15]:
#webpage
url = 'https://www.naukri.com/'  
driver.get(url)

#Enter "Data scientist" in "Skill,Designations,Comapnies" field
search_job = driver.find_element_by_id('qsb-keyword-sugg')
search_job
search_job.send_keys("Data Scientist")

#click search button
search_btn = driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

#enter"Delhi/NCR"in "enter the location"field and salary.
search_loc = driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys("Delhi/NCR")

search_loc = driver.find_element_by_id('qsb-location-sugg')
search_loc.send_keys("salary")

#scrape the job-title
titles_tags= driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags
job_titles=[]
for i in titles_tags:
    job_titles.append(i.text)
job_titles

#scrape the job_location.
locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']//span")
locations_tags
locations_list=[]
for i in locations_tags:
    locations_list.append(i.text)
locations_list

#scrape the campany_name.
companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags
company_names=[]

for i in companies_tags:
    company_names.append(i.text)
company_names

#scrape the experiance_requried.
experiance_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")
experiance_tags
experiance_list=[]
for i in experiance_tags:
    experiance_list.append(i.text)
experiance_list

#top 10 job list
titles_tags[:10]

print(len(job_titles),len(locations_list),len(company_names),len(experiance_list))

#DataFrame
jobs=pd.DataFrame({})
jobs['title']=job_titles
jobs['location']=locations_list
jobs['campany']=company_names
jobs['experiance_requried']=experiance_list

In [27]:
jobs

,title,location,campany,experiance_requried
0,Senior Data Scientist,"Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",Fractal Analytics,4-8 Yrs
1,Co-Founder - Principal Data Scientist/Senior D...,"Gurgaon/Gurugram, Delhi / NCR",Benovymed Healthcare Private Limited,2-7 Yrs
2,Data Scientist,"Mumbai, New Delhi",POPxo,2-4 Yrs
3,Data Scientist,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",Replicon Software,5-10 Yrs
4,Data Scientist,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",Replicon Software,5-10 Yrs
5,Data Scientist - NLP/ML/Python,Gurgaon/Gurugram,Elixir Web Solutions,4-8 Yrs
6,Data Scientist - Insurance - IIM/IIT/NIT,Gurgaon/Gurugram,Huquo Consulting Pvt. Ltd,12-16 Yrs
7,Data Scientist - Insurance - IIM/ IIT/ NIT,Gurgaon/Gurugram,Huquo Consulting Pvt. Ltd,6-10 Yrs
8,Data Scientist - BFSI,"Gurgaon/Gurugram, Delhi / NCR",Huquo Consulting Pvt. Ltd,3-8 Yrs
9,Data Scientist - Machine Learning/ NLP,Gurgaon/Gurugram,TalPro,2-6 Yrs
10,SAVP - Data Scientist - Data Science Team - In...,Gurgaon/Gurugram,Huquo Consulting Pvt. Ltd,8-13 Yrs
11,Farfetch - Senior Data Scientist,New Delhi,Farfetch,5-9 Yrs
12,Data Scientist: Machine Learning,"Gurgaon/Gurugram, Delhi / NCR, Mumbai (All Areas)",Fractal Analytics,3-7 Yrs
13,Co-Founder & Principal Data Scientist/Senior S...,"Gurgaon/Gurugram, Delhi / NCR",Benovymed Healthcare,2-7 Yrs
14,Data Scientist / Data Analyst - Mobile Gaming ...,Gurgaon/Gurugram,WITZEAL TECHNOLOGIES PRIVATE LIMITED,3-7 Yrs
15,Senior Data Scientist,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",ZAZMIC INDIA PRIVATE LIMITED,3-8 Yrs
16,Data Scientist - Machine Learning - Ecommerce,Gurgaon/Gurugram,Talpro,2-6 Yrs
17,Data Analyst/Scientist- (Counterparty Credit r...,"Hyderabad/Secunderabad, Ahmedabad, Bangalore/B...",GENPACT India Private Limited,4-9 Yrs
18,Data Scientist (Hadoop/ Redshift/ BigQuery),Noida,Jubna,3-5 Yrs
19,Manager- Data Scientist,Gurgaon/Gurugram,Amway India Enterprises Pvt Ltd,6-11 Yrs

Question 4-scrape the data from glassdore

In [7]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")

In [8]:
#1webpage
url = 'https://www.naukri.com/'  
driver.get(url)

#Enter "Data scientist" in "Skill,Designations,Comapnies" field
search_job = driver.find_element_by_id('qsb-keyword-sugg')
search_job
search_job.send_keys("Data Scientist")

#click search button
search_btn = driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [12]:
#fetching urls
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"):
    urls.append(i.get_attribute("href"))
    
len(urls)
urls

job_title=[]
job_list=[]
job_description=[]

for i in urls[:10]:
    driver.get(i)
    time.sleep(3)
    #fetching job title
    try:
        job=driver.find_element_by_xpath("//h1[@class='jd-header-title']")
        job_title.append(job.text)
    except NoSuchElementException:
        job_title.append('-')
        
        #fetching job description
    try:
        job_desc= driver.find_element_by_xpath("//section[@class='job-desc']")
        job_descripton.append(job_desc.text)
    except:
        job_description.append('-')
        
print(len(job_title))
print(len(job_description))  

job_title
job_description

#DataFrame
jobs=pd.DataFrame({})
jobs['title']=job_titles
jobs['location']=locations_list
jobs['campany']=company_names
jobs['description']=job_description

0
0

NameError: name 'locations_list' is not defined

In [11]:
jobs

Empty DataFrame
Columns: [title]
Index: []

Question no.5 scrape the data from webpage glassdoor

In [13]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")
#webpage
url = 'https://www.glassdoor.co.in/Salaries/index.htm'  
driver.get(url)

#Enter "Data scientist" in "Job Title ,keyword,Company" field
search_job = driver.find_element_by_id('KeywordSearch')
search_job
search_job.send_keys("Data Scientist")

#enter"Noida"in "enter the location"field.
search_loc = driver.find_element_by_id('LocationSearch')
search_loc.send_keys("Noida")

#click search button
search_btn = driver.find_element_by_xpath("//button[@class='gd-btn-mkt']")
search_btn.click()

#fetching urls
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='jobLink css-1rd3saf eigr9kq2']"):
    urls.append(i.get_attribute("href"))
    
len(urls)

#fetching all urls
urls

#empty list
min_salary=[]
max_salary=[]
company_name=[]
average_salary=[]
company_rating=[]



for i in urls[:10]:
    driver.get(i)
    time.sleep(5)

    #fetching min Salary 
try:
        min_salary= driver.find_element_by_xpath("//a[@class='']/span")
        min_salary.append(min_salary.text)
        
except:
        min_salary.append('-')        
          #fetching max Salary 
try:
        max_salary= driver.find_element_by_xpath("//a[@class='']/span")
        max_salary.append(max_salary.text)
except:
        max_salary.append('-')    
#fetching company_name 
try:
        company_name= driver.find_element_by_xpath("//a[@class='css-l2wjgv e1n63ojh0 jobLink']/span")
        company_name.append(company_name.text)
except:
        company_name.append('-')
        
        #fetching job posting date
try:
        average_salary= driver.find_element_by_xpath("//div[@class='d-flex align-items-end pl-std css-mi55ob']")
        average_salary.append(average_salary.text)
except:
       average_salary.append('-')
        
     #fetching company_rating
try:
        company_rating= driver.find_element_by_xpath("//a[@class='css-19pjha7 e1cjmv6j1']/span")
        company_rating.append(company_rating.text)
except:
        company_rating.append('-')
        

print(len(min_salary))
print(len(max_salary))
print(len(company_name))
print(len(average_salary))
print(len(company_rating)) 
 

#DataFrame
jobs=pd.DataFrame({})
jobs['min_salary']=min_salary
jobs['max_salary']=max_salary
jobs['company_name']=company_name
jobs['average_salary']=average_salary
jobs['company_rating']=company_rating
jobs


I am not able to fetch the data after this

In [22]:
jobs

  min_salary max_salary company_name average_salary company_rating
0          -          -            -              -              -

Question no.6-Scrape the data from flipkart

In [27]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")
#webpage
url = 'https://www.flipkart.com/'  
driver.get(url)


#Enter sunglasses in search field
search_job = driver.find_element_by_xpath('//input[@ class="_3704LK"]')
search_job.send_keys("sunglasses")

#click search icon
search_btn = driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn.click()

#fetching urls
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='IRpwTa']"):
    urls.append(i.get_attribute("href"))
    
len(urls)

urls

#empty list
sunglasse_brand=[]
sunglasse_description=[]
sunglasse_price=[]
sunglasse_discount=[]

#fetching the details

for i in urls[:100]:
    driver.get(i)
    time.sleep(3)
    #fetching brand
    try:
        sunglass=driver.find_element_by_xpath("//h1[@class='yhB1nd']")
        sunglass_brand.append(sunglass.text)
    except NoSuchElementException:
        sunglass_brand.append('-')
        
        #fetching product description
    try:
        sunglass_desc= driver.find_element_by_xpath("//h1[@class='dyC4hf pZkvcx']")
        sunglass_descripton.append(sunglass_desc.text)
    except:
        sunglass_description.append('-')
        
          #fetching price
    try:
        sunglass_price= driver.find_element_by_xpath("//div[@class='_1V_ZGU pZkvcx']//span")
        sunglass_price.append(sunglass_price.text)
    except:
        sunglass_price.append('-')
        
          #fetching discounts
    try:
        sunglass_disc= driver.find_element_by_xpath("//div[@class='_25b18c']")
        sunglass_discount.append(sunglass_disc.text)
    except:
        sunglass_discount.append('-')
        
print(len(sunglass_brand),len(sunglass_description),len(sunglass_price),len(sunglass_discount))


#DataFrame
sunglasses=pd.DataFrame({})
sunglasses['brand']=sunglass_brand
sunglasses['description']=sunglass_description
sunglasses['price']=sunglass_price
sunglasses['discount']=sunglass_discount

ElementClickInterceptedException: Message: element click intercepted: Element <button class="L0Z3Pu" type="submit">...</button> is not clickable at point (556, 28). Other element would receive the click: <div class="_36HLxm col col-3-5">...</div>
  (Session info: chrome=91.0.4472.124)

In [28]:
sunglasses

NameError: name 'sunglasses' is not defined

Question no.7-scape 100 reviews data from  flipkart.com for iphone 11 phone.

In [33]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")
#Q1.webpage
url = 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includesearpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKC TSVZAXUHGREPBFGI&marketplace.'  
driver.get(url)

#empty list
phone_rating=[]
review_summary=[]
full_review=[]

#fetching phone rating
try:
        phone=driver.find_element_by_xpath("//div[@class='_2_R_DZ]//span")
        phone_rating.append(phone_rating.text)
except NoSuchElementException:
        phone_rating.append('-')
               
        #fetching phone review
try:
        phone_review= driver.find_element_by_xpath("//div[@class='col-12-12']")
        phone_review.append(phone_review.text)
except:
        phone_review.append('-')
        
          #fetching full summary
try:
        review_summary= driver.find_element_by_xpath("//div[@class='_2418kt']")
        review_summary.append(review_summary.text)
except:
        review_summary.append('-')
print(len(phone_rating),len(review_summary),len(full_review))

#DataFrame
jobs=pd.DataFrame({})
jobs['phone_rating']=phone_rating
jobs['review_summary']=review_summary
jobs['full_review']=full_review
    
    
jobs

AttributeError: 'WebElement' object has no attribute 'append'

Question no.8-Scrap data for first 100 sneakers you find when you visit flipkart.com

In [34]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")
#Q1.webpage
url = 'https://www.flipkart.com/'  
driver.get(url)

#search sneakers
search_job = driver.find_element_by_xpath('//input[@ class="_3704LK"]')
search_job.send_keys("sneakers")

#Click the search button
search_btn = driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn.click()

#fetching urls
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='_2r_T1I']"):
    urls.append(i.get_attribute("src"))
len(urls)
urls

#empty list
sneakers_brand=[]
sneakers_description=[]
sneakers_price=[]
sneakers_discount=[]

#fetching the details

for i in urls[:100]:
    driver.get(i)
    time.sleep(3)
    #fetching brand
    try:
        sneakers=driver.find_element_by_xpath("//div[@class='_2WkVRV']")
        sneakers_brand.append(sneakers.text)
    except NoSuchElementException:
        sneakers_brand.append('-')
        
        #fetching product description
    try:
        sneakers_desc= driver.find_element_by_xpath("//a[@class='IRpwTa']")
        sneakers_descripton.append(sneakers_desc.text)
    except:
        sunglasses_description.append('-')
        
          #fetching price
    try:
        sneakers_price= driver.find_element_by_xpath("//div[@class='_30jeq3']")
        sneakers_price.append(sneakers_price.text)
    except:
        sneakers_price.append('-')
        
          #fetching discounts
    try:
        sneakers_disc= driver.find_element_by_xpath("//div[@class='_3Ay6Sb']")
        sneakers_discount.append(sneakers_disc.text)
    except:
        sneakers_discount.append('-')
        
print(len(sneakers_brand),len(sneakers_description),len(sneakers_price),len(sneakers_discount))


#DataFrame
sneakers=pd.DataFrame({})
sneakers['brand']=sunglasses_brand
sneakers['description']=sunglasses_description
sneakers['price']=sunglasses_price
sneakers['discount']=sunglasses_discount

ElementClickInterceptedException: Message: element click intercepted: Element <button class="L0Z3Pu" type="submit">...</button> is not clickable at point (556, 28). Other element would receive the click: <div class="_36HLxm col col-3-5">...</div>
  (Session info: chrome=91.0.4472.124)

In [35]:
sneakers

NameError: name 'sneakers' is not defined

Question no.9-Scrape the data from Myntra.com

In [36]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")
#Q9.webpage
url = 'https://www.myntra.com/shoes/'  
driver.get(url)
#filter to Rs.6649 to Rs.13099
filter_button=driver.find_elements_by_xpath("//label[@class='common-customCheckbox vertical-filters-label']")
for i in filter_button:
    if i.text=='Rs.6649 to Rs.13099':
        i.click()
        break
        
# Color filter to Black
filter_button=driver.find_elements_by_xpath("//label[@class='common-customCheckbox vertical-filters-label']")
for i in filter_button:
    if i.text=='Black':
        i.click()
        break
        
         #fetching urls
for i in urls[:100]:
for i in driver.find_elements_by_xpath("//a[@target='_blank']"):
    urls.append(i.get_attribute("href")
                
len(urls)
urls

IndentationError: expected an indented block (<ipython-input-36-c2681370f25a>, line 22)

Question No.10-Scrape the data from amazon.in

In [37]:
#web driver
driver = webdriver.Chrome("chromedriver.exe")
#Q10.webpage
url = 'https://www.amazon.com/'  
driver.get(url)


#Enter "Laptop" in search field
search_job = driver.find_element_by_id('twotabsearchtextbox')
search_job.send_keys("Laptop")


#Click the search button
search_btn = driver.find_element_by_id('nav-search-submit-button')
search_btn.click()

# filterthe core i7
filter_button=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")
for i in filter_button:
    if i.text=='Intel Core i7':
        i.click()
        break
        
 # filter core i9 
filter_button=driver.find_elements_by_xpath("//a[@class='a-link-normal s-navigation-item']/span")
for i in filter_button:
    if i.text=='Intel Core i9':
        i.click()
        break
        
 #fetching urls
urls=[]
for i in driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']"):
    urls.append(i.get_attribute("href"))
    
len(urls)
#fetching all urls
urls
#empty list
laptop_title=[]
laptop_rating=[]
laptop_price=[]

for i in urls[:10]:
    driver.get(i)
    time.sleep(5)
#fetching laptop title
try:
        laptop=driver.find_element_by_xpath("//h1[@class='a-size-large a-spacing-none']")
        laptop_title.append(laptop.text)
except NoSuchElementException:
        laptop_title.append('-')
        
#fetching laptop rating 
try:
        laptop_rating= driver.find_element_by_xpath("//a[@class='a-icon-alt']/span")
        laptop_rating.append(laptop_rating.text)
except:
        laptop_rating.append('-')
        
     #fetching laptop price
try:
        laptop_price= driver.find_element_by_xpath("//id[@class='a-size-medium a-color-price priceBlockBuyingPriceString']//span")
        laptop_price.append(laptop_price.text)
except:
        laptop_price.append('-')

print(len(laptop_title))
print(len(laptop_rating)) 
print(len(laptop_price))       

#DataFrame
laptops=pd.DataFrame({})
laptops['title']=laptop_title
laptops['rating']=laptop_rating
laptops['price']=laptop_price

1
1
1

In [38]:
laptops

                                               title rating price
0  Acer Aspire 5 A515-55-378V, 15.6" Full HD Disp...      -     -